drewnoakes/metadata-extractor-dotnet

MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDescriptor.cs
This commit corrects Issue #18. Other GetEvDescription calls were tested, but should be verified. The double cast on values[2] may not be necessary but left it just in case.
=> cast Nikon EV byte array values to sbyte (signed byte) to correct calc

MetadataExtractor/Formats/Exif/ExifDirectoryBase.cs, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
In .NET, addresses the other half of drewnoakes/metadata-extractor#151
IFD0 was missing the ApplicationNotes tag (0x02BC) which can apparently hold XMP data. This assumes it is always XMP in there, but I can't 100% confirm this.
=> Handle IFD0 ApplicationNotes tag (0x02BC)  as XMP

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/CanonMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawDevelopmentMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawDevelopmentMakernoteDirectory.cs, MetadataExtractor/MetadataExtractor.Portable.csproj, MetadataExtractor/MetadataExtractor.net35.csproj, MetadataExtractor/MetadataExtractor.net45.csproj
Implements another Olympus subifd (Raw Development, 0x2030) as a directory. Cleans-up more format 13 errors from the images project.
=> Olympusrawdev

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawDevelopment2MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawDevelopment2MakernoteDirectory.cs, MetadataExtractor/MetadataExtractor.Portable.csproj, MetadataExtractor/MetadataExtractor.net35.csproj, MetadataExtractor/MetadataExtractor.net45.csproj
Implements another Olympus subifd (Raw Development 2, 0x2031) as a directory. However, there are no images in the current images repository to test. It's a short directory so not a huge deal.
This used a copy/paste of GetFilterDescription AND _filters from OlympusCameraSettingsMakernoteDescriptor. You might decide how best to share these in the "Olympus" set, as there could be other directories that use them.
=> Olympusrawdev2

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusImageProcessingMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusImageProcessingMakernoteDirectory.cs, MetadataExtractor/MetadataExtractor.Portable.csproj, MetadataExtractor/MetadataExtractor.net35.csproj, MetadataExtractor/MetadataExtractor.net45.csproj
Implements another Olympus subifd (Image Processing, 0x2040) as a directory. Cleans-up a good number of format 13 errors from the images project.
=> Olympus Image Processing subifd (0x2040) directory

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusFocusInfoMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusFocusInfoMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusMakernoteDirectory.cs, MetadataExtractor/MetadataExtractor.Portable.csproj, MetadataExtractor/MetadataExtractor.net35.csproj, MetadataExtractor/MetadataExtractor.net45.csproj
Implements an Olympus subifd (Focus Info, 0x2050) as a directory. Cleans-up the remaining format 13 errors from the images project. Other notes:
- There are two "Serial Number" tags in the main Olympus Makernote. This corrects the list and reassigns TagFirmware to value 0x0405
- FocusInfo tag 0x4000 is a subifd pointing to a second OlympusMakernoteDirectory. Added that to ExifTiffHandler.TryEnterSubIfd. That corrects a few other format 13 errors as well.
=> Olympus Focus Info subifd (0x2050) directory

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/LeicaType5MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/LeicaType5MakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/SamsungType2MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/SamsungType2MakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/SonyType1MakernoteDescriptor.cs
Start to address drewnoakes/metadata-extractor#202 although only a few representative images were tested. These images were used (tried to pick one of each kind mentioned in the issue):
http://rawsamples.ch/raws/sony/RAW_SONY_RX10.ARW
http://img.photographyblog.com/reviews/leica_x_typ_113/photos/leica_x_typ_113_01.jpg
http://img.photographyblog.com/reviews/samsung_nx500/photos/samsung_nx500_01.jpg
This PR will need revision later to fully address the issue, and then converted to Java by someone. I ran this code against the images repo and there are some notable differences in makernote output and some 0x0000 errors being passed over.
Also, in implementing this, 0x0000 tags with no associated bytes (byteCount=0) are handled differently to cleanup errors with these specific images. Please …
=> Handle more RAW makernotes from Sony, Leica, and Samsung.

MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/PrintIMDescriptor.cs, MetadataExtractor/Formats/Exif/PrintIMDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/CasioType2MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusCameraSettingsMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusCameraSettingsMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusEquipmentMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusImageProcessingMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusImageProcessingMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawInfoMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusRawInfoMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/PanasonicMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/SanyoMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/SonyType1MakernoteDirectory.cs, MetadataExtractor/TagDescriptor.cs, MetadataExtractor/Util/FileTypeDetector.cs
- Higher coverage of Olympus tags and ifd's
- Added Olympus RawData ifd
- "MMOR" detected for ORF in FileTypeDetector
- PrintIM implemented for all directories containing the 0x0E00 tag
- As of 11/25/16, tested all Olympus RAW files from http://www.rawsamples.ch/index.php/en/olympus
Resolves #32 and amends drewnoakes/metadata-extractor#175
Let me know if you have any questions or problems.
=> More Olympus RAW and IFD coverage

MetadataExtractor/DirectoryExtensions.cs, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/ReconyxHyperFireMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/ReconyxHyperFireMakernoteDirectory.cs, MetadataExtractor/Formats/Exif/makernotes/ReconyxUltraFireMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/ReconyxUltraFireMakernoteDirectory.cs, MetadataExtractor/Util/ByteConvert.cs
Should be pretty straightforward.  A common base class between the HyperFire and UltraFire makernotes seems desirable but---as tag offsets differ, tag values are of different types and formats, and tag names aren't always the same---is not trivial to express safely and clearly.
=> support Reconyx UltraFire makernote

MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs, MetadataExtractor/Formats/Exif/ExifDirectoryBase.cs, MetadataExtractor/Formats/Exif/ExifImageDescriptor.cs, MetadataExtractor/Formats/Exif/ExifImageDirectory.cs, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
drewnoakes/metadata-extractor#223
- Bug fix in ExifDescriptorBase for a missing subfiletype description.
- Added Page Number (0x0129) tag to ExifDescriptorBase
- First go at detecting and displaying multipage tiff images
The problems I see with this PR:
- The new check in HasFollowerIfd() isn't based on a concrete way of knowing it's an 'image' that I can find so far. It's mostly intuition that the page number tag won't exist in other cases.
- Adding additional ExifIfd0Directory's was my first solution. That seemed wrong since these aren't IFD0 and instead created a new directory (ExifImageDirectory). I can't say either way whether that's a good solution, better name, etc.
- Using "PushDirectory" in this case can create a very long indented output of the structure
It makes significant …
=> Add Follower IFD check for multipage tiff files

MetadataExtractor/DirectoryExtensions.cs, MetadataExtractor/Formats/Iptc/IptcReader.cs, MetadataExtractor/Formats/Iptc/Iso2022Converter.cs, MetadataExtractor/Formats/Png/PngMetadataReader.cs, MetadataExtractor/IO/SequentialReader.cs, MetadataExtractor/StringValue.cs
- port of drewnoakes/metadata-extractor@184ce9c
- refactor IPTCReader.ProcessTag to use StringValue and get closer to Java output
- Added some StringValue methods to DirectoryExtensions and SequentialReader
- DeflateStream implements RFC 1951, but not RFC 1950. Strip first two bytes of input array to make it 'deflate' compatible (should watch for any new issues in the future with this)
- If StringValue's ToInt32 converter can't parse the input as a string, loop through the bytes and make an int out of them (similar to the Java project's getInteger method)
=> IPTC output fixes and additions + Deflate fix.

MetadataExtractor.Tests/MetadataExtractor.Tests.csproj
When xUnit was releasing 2.2.0 they dropped support for net451, see https://xunit.github.io/release-notes/2017-02-19.html
This PR contains updated TFM to net452 that only is for test-project so the class library will still compuled for lower TFM. You can see that in this https://ci.appveyor.com/project/Tasteful/metadata-extractor-dotnet/build/2.0.3 build.
If removing the `test_script` from `appveyor.yml` only the `net452` build is executing, with the `test_script` both test for `net452` and `netcoreapp1.0` is executed.
=> Execute .net45 and .netcoreapp1.0 tests

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/ReconyxUltraFireMakernoteDirectory.cs
Three small changes to conform match Reconyx's MapView software.  Coded these back in January but neglected to put in the pull.  They passed tests at the time and build clean on current bits but have only been manually tested via MetadataExtractor due to #93.  Therefore falling back to AppVeyor alone.
=> adjust Reconyx UltraFire makernote to match MapView

MetadataExtractor/MetadataExtractor.csproj
This eliminates dependencies (excluding XmpCore) on modern runtimes.
=> Cross target NETSTANDARD 2.0

MetadataExtractor/IO/SequentialByteArrayReader.cs, MetadataExtractor/IO/SequentialStreamReader.cs
Bugfix: IsCloserToEnd returns true on reading last byte, should be false. IsCloserToEnd must return true if we read after EOF only.
=> Bugfix: IsCloserToEnd returns true on reading last byte, should be false

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs, MetadataExtractor/Formats/QuickTime/QuickTimeReaderExtensions.cs, MetadataExtractor/IO/SequentialReader.cs
Rotation values are now all positive ranging from 0 to 360 degree clockwise.
Fixed reading matrix values.
=> Fixed rotation and matrix values for quicktime.

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
First: Thanks for the work you put into this library!
DJI Makernote parsing was already in the code base, but wasn't called from ExifTiffHandler.cs. If I understand the code correctly :)
Added the model check & tested with photos from DJI FC6520, FC6310 and FC330, and works great.
And an unrelated questions: looks like there is activity in this repo, but there hasn't been a release since 2.0.0. Am I missing something? Anything I could help?
=> Added DJI to ExifTiffHandler.cs, so DJI makernotes are parsed

MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs
fix ExifDescriptorBase.GetBrightnessValueDescription and ExifDescriptorBase.GetSubjectDistanceDescription to match Java output in edge cases
=> ExifDescriptorBase Java ports

MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDescriptor.cs
The Java version of this should get updated with the null check
=> Fix NikonType2 GetPowerUpTimeDescription. It isn't an int64

MetadataExtractor.Tools.FileProcessor/Program.cs
FileProcessor's ProcessDirectory method was change to use the 'stream' version of reading metadata at some point. However, ImageMetadataReader.ReadMetadata(Stream) won't automatically add a FileMetadataReader directory which causes a discrepancy when processing the entire image library.
=> Manually add a FileMetadataReader directory to match Java output

MetadataExtractor.Tests/Formats/Bmp/BmpReaderTest.cs, MetadataExtractor/Formats/Bmp/BmpHeaderDescriptor.cs, MetadataExtractor/Formats/Bmp/BmpHeaderDirectory.cs, MetadataExtractor/Formats/Bmp/BmpMetadataReader.cs, MetadataExtractor/Formats/Bmp/BmpReader.cs, MetadataExtractor/ImageMetadataReader.cs, MetadataExtractor/Util/FileTypeDetector.cs
I'm not really impressed with how the enums + description worked in the Java implementation, but it is what it is. Maybe that should be reviewed a little. Using the special enum methods that Java supports kind of breaks the mold for how the library stores and returns descriptions.
=> Port extended BMP support from Java

MetadataExtractor.Tests/Formats/Png/PngDescriptorTest.cs, MetadataExtractor/Formats/Png/PngDescriptor.cs
Port of drewnoakes/metadata-extractor#325 :
"Problem:
PngDescriptor.GetBackgroundColorDescription() always returns null even if "TagBackgroundColor" has some value. This is because the code checks the "TagColorType" value, but it exists in the different directory (PNG-IHDR).
Solution:
Return the description based on the length of the byte array."
=> Port of #325 from Java

MetadataExtractor/Formats/Avi/AviRiffHandler.cs
used Ticks because TimeSpan().ToString(string format) isn't available in netstandard1.3
=> Fix Avi Duration output hour. "HH" is 24 hour time

MetadataExtractor/Formats/Gif/GifControlDescriptor.cs, MetadataExtractor/Formats/Gif/GifControlDirectory.cs, MetadataExtractor/Formats/Gif/GifReader.cs
Todo: backport GifControlDescriptor "{value}" addition to Java
Todo: backport to Java GifReader --  directory.Set(GifControlDirectory.TagUserInputFlag, (packedFields & 2) == 2);
=> Port GifControlDirectory additions from Java

MetadataExtractor.Tests/Formats/Xmp/XmpReaderTest.cs, MetadataExtractor.Tools.FileProcessor/TextFileOutputHandler.cs, MetadataExtractor/Formats/Xmp/XmpDirectory.cs
- process only leafnodes for XMP data both in XmpDirectory and text file output
- use consistent new lines in TextFileOuputHandler
Before this change, .NET would go directly through XmpDirectory.XmpMeta for normal processing and display. Namespace nodes are also present in this collection and output lines with blank values. This isn't an error, but they're always like this and Java ignores them by setting an iterator option. With the change, text file output is consistent with Java and removes scores of discrepancies.
Note that XmpMeta is using an Iterator instance with a null IteratorOptions parameter internally for the Properties property, meaning there is no more of a performance hit for this than calling Properties.
=> Java port - Process only leafnodes for XMP data

MetadataExtractor.Tests/Formats/Jpeg/HuffmanTablesDirectoryTest.cs, MetadataExtractor/Directory.cs, MetadataExtractor/Formats/Bmp/BmpReader.cs, MetadataExtractor/Formats/Jpeg/HuffmanTablesDescriptor.cs, MetadataExtractor/Formats/Jpeg/HuffmanTablesDirectory.cs, MetadataExtractor/Formats/Jpeg/JpegDhtReader.cs, MetadataExtractor/Formats/Jpeg/JpegDnlDescriptor.cs, MetadataExtractor/Formats/Jpeg/JpegDnlDirectory.cs, MetadataExtractor/Formats/Jpeg/JpegDnlReader.cs, MetadataExtractor/Formats/Jpeg/JpegMetadataReader.cs, MetadataExtractor/Formats/Jpeg/JpegSegmentType.cs, MetadataExtractor/IO/SequentialByteArrayReader.cs, MetadataExtractor/IO/SequentialReader.cs, MetadataExtractor/IO/SequentialStreamReader.cs, MetadataExtractor/Util/ByteArrayUtil.cs
Port of drewnoakes/metadata-extractor#231
=> Port of Java #231: Implement Huffman Tables directory and reader

MetadataExtractor/Directory.cs, MetadataExtractor/Formats/Png/PngMetadataReader.cs
Good metadata is lost when PNG chunks encounter processing errors. Refactor so errors can be recorded while preserving this good metadata.
=> Catch PNG chunk processing errors

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs, MetadataExtractor/Formats/QuickTime/QuickTimeTiffHandler.cs, MetadataExtractor/Formats/Tiff/DirectoryTiffHandler.cs
This is my stab at a minimal CR3 support.
CR3 is based on ISO/IEC 14496-12, ~~which means it is detected as QuickTime~~. The moov container wraps 4 TIFF IFDs (and other data, which will be ignored).
**Edit:** Added CRX file type; see below.
**Edit 2:** Fixed CMT2 directory type.
=> Add crude CR3 support

MetadataExtractor/Formats/Png/PngMetadataReader.cs
Fixes #204.
PNG has "raw profiles" via which it can store additional formats such as XMP, Exif, ICC and IPTC. This adds support for them.
=> Support PNG raw profiles

MetadataExtractor/Util/FileTypeDetector.cs
This also restores backwards compatibility (FileType.QuickTime for unknown major brands)
=> Uniform QuickTime and RIFF checkers

MetadataExtractor.Tests/Formats/Iptc/IptcReaderTest.cs, MetadataExtractor.Tests/Formats/Photoshop/PsdReaderTest.cs, MetadataExtractor.Tests/Formats/Png/PngMetadataReaderTest.cs, MetadataExtractor.Tools.FileProcessor/Program.cs, MetadataExtractor.Tools.FileProcessor/TextFileOutputHandler.cs, MetadataExtractor/Directory.cs, MetadataExtractor/MetadataExtractor.csproj
Without this, callers using `netstandard2.0` builds see execptions for certain files that need `windows-1252` encoding.
=> Register encodings under netstandard2.0 as well

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
The Description of the Tag QuickTime Compatible Brands is not a string, but a list. This results in  a description of "System.Collections.Generic.List`1[System.String]}"
In order to get the values of the compatible brands, you could use a string join.
[My PR did not compile, sorry about that. I should have opened an issue instead of a PR without testing]
=> QuickTime Compatible Brands value correction

Directory.Build.props
Now that VS2019 16.3 has gone GA, we don't need to opt in to a specific compiler version.
This PR will also validate that CI has a sufficient default compiler.
=> Use default compiler

Directory.Build.props
Assuming this is configured correctly, it allows VS users to navigate into downloaded sources for the library while debugging.
=> Enable SourceLink

MetadataExtractor/Formats/Photoshop/Knot.cs, MetadataExtractor/Formats/Photoshop/PhotoshopDescriptor.cs, MetadataExtractor/Formats/Photoshop/PhotoshopDirectory.cs, MetadataExtractor/Formats/Photoshop/PhotoshopReader.cs, MetadataExtractor/Formats/Photoshop/Subpath.cs
port of Java PR drewnoakes/metadata-extractor#267
=> Port of Java PR #267 - Clipping Path Name / Path Information Extraction

MetadataExtractor.Tools.FileProcessor/Program.cs
Closes #89
With this change I've got two changes in the test image repo:
```diff
jpg/metadata/dotnet/Reconyx HF2 Pro Covert.jpg.txt
@@ -37,7 +37,7 @@ TYPE: JPEG
-[Reconyx HyperFire 2 Makernote - 0x0030] Firmware Date = 24/08/2018
+[Reconyx HyperFire 2 Makernote - 0x0030] Firmware Date = 08/24/2018
tif/ImageTestSuite/metadata/dotnet/efb780f70a7d94fa98adfc98d2aa8d50.tif.txt
@@ -56,7 +56,7 @@ TYPE: TIFF
-[Exif SubIFD - 0x9206] Subject Distance = ∞ metres
+[Exif SubIFD - 0x9206] Subject Distance = Infinity metres
```
=> Use invariant culture for regression tests

MetadataExtractor/Formats/Photoshop/DuckyReader.cs
Fixes the problem with [`jpg/NegativeArraySizeException.DuckyReader.extract.mp3`](https://github.com/drewnoakes/metadata-extractor-images/commit/4244161122711b3cfdc0a317b2c699cfd94ba867#diff-ed6cbf568225fbeb5fb842e85094e967) from #196
=> Prevent negative length in "Ducky" data

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataHeaderDirectory.cs, MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
Does not support Optional Item_info atom or Optional name atom inside the the Value Atom as described in the spec as none of the sample data I had access to had these attributes.
=> Add Support for Quicktime metadata incl GPS and CreationDate

MetadataExtractor/Formats/QuickTime/QuickTimeTiffHandler.cs
We use C# 8 nullable reference types now.
=> Remove redundant annotation

MetadataExtractor/ImageMetadataReader.cs
This matches the behaviour of the Java library.
=> Don't throw for known but unsupported file types

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
Removed the limitation of only default locale is supported. Now, all fields are retrieved, but without locale tag. This should be supported in future. For now, at least, we have the description metadata, which is useful for blind people, I.E., in Apple iPhone, when users labeled the pictures with Voice Over.
=> Added quick time metadata with no default locale.

MetadataExtractor/Formats/Heif/HeifMetadataReader.cs, MetadataExtractor/Formats/Iso14496/BoxTypes.cs
- Added the xmp directory in HEIF format (iso-14496). Related to issue #231.
- Fixed a bug where under certain circumstances, the bytes of the exif directory were extended to the next box.
- Fixed an unknown issue when the segments to be parsed start before last position after reading all boxes. Reordered segments bassed on extended offset, not only base offset, so the read will always be in sequential order. This last change fixes the exception thrown in the image file heic/Issue 487.heic.
=> - Added the xmp directory in HEIF format (iso-14496).

MetadataExtractor/Formats/Icc/IccDirectory.cs
This is the copyright of the profile. The new name makes it clear what the copyright applies to and more closely matches other tag names in the ICC directory.
=> Rename ICC Profile Copyright tag

.editorconfig, MetadataExtractor.Tests/DirectoryTest.cs, MetadataExtractor/DirectoryExtensions.cs
Closes #138
There are still some string concatenation that do not use an invariant output format. But the main points of the issue are fixed.
=> Culture sensitivity

MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
=> Interpret QuickTime metadata dates

MetadataExtractor/TagDescriptor.cs
Reads first 8 bytes for character encoding recognition to comply with
EXIF standard.
It's not necessary to read 10 bytes at the beginning. Reading these two
extra bytes could lead to missing bytes and the end. Switching the byte
order for UNICODE to big-endian solves the issue with 8 and 10 bytes
reads.
Only for ASCII NULL termination is done, "since the type is not ASCII,
NULL termination is not necessary".
Closes #173
=> Interpret UserComment character code

MetadataExtractor/Formats/Png/PngChunkReader.cs
Previously the code would read a byte[] for every PNG chunk, irrespective of whether it was going to be stored. With this change, these arrays are only allocated when they will actually be needed.
This is the .NET port of https://github.com/drewnoakes/metadata-extractor/pull/535
=> Reduce allocation when reading PNG chunks

MetadataExtractor/Formats/Iptc/IptcDirectory.cs
This fixes IPTC date/time parsing so that it no longer depends upon the environment's culture.
This also fixes the broken CI build.
=> Use invariant culture when parsing IPTC dates/times

Build.ps1, Directory.Build.props, MetadataExtractor.sln, MetadataExtractor/MetadataExtractor.csproj, README.md
Moves to a single strong-named package, and starts preparation for verison 2.5.0.
=> Version 2.5.0

MetadataExtractor/Formats/Photoshop/DuckyReader.cs
A few lines down from here, the number is reduced by four then checked whether the value is less than zero. An unsigned value can never be less than zero. The fix is to declare this as signed.
=> Fix unsigned comparison

MetadataExtractor.Samples/FlirSamples.cs, MetadataExtractor.Samples/MetadataExtractor.Samples.csproj, MetadataExtractor.Tools.FileProcessor/MetadataExtractor.Tools.FileProcessor.csproj, MetadataExtractor.sln.DotSettings, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/FlirMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/FlirMakernoteDirectory.cs, MetadataExtractor/Formats/Flir/FlirCameraInfoDescriptor.cs, MetadataExtractor/Formats/Flir/FlirCameraInfoDirectory.cs, MetadataExtractor/Formats/Flir/FlirHeaderDirectory.cs, MetadataExtractor/Formats/Flir/FlirMainTagType.cs, MetadataExtractor/Formats/Flir/FlirRawDataDirectory.cs, MetadataExtractor/Formats/Flir/FlirReader.cs, MetadataExtractor/Formats/Jpeg/JpegMetadataReader.cs, MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, MetadataExtractor/Util/DateUtil.cs
This PR adds support for various kinds of FLIR metadata.
- FLIR Makernote
- FLIR metadata from JPEG APP1 segments
- Header info
- Camera info
- Raw thermal image info
By setting `FlirReader.ExtractRawThermalImage` to `true`, it's possible to extract the raw thermal data as well. This data has been observed in both raw `int16` data and PNG encoded data.
=> Add support for FLIR thermal image metadata

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
This fixes an issue where XMP data was not being extracted from some DJI images, and allows presentation of data such as:
```
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:AbsoluteAltitude = -30.037239
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:RelativeAltitude = 19.700001
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalRollDegree = 0.000000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalYawDegree = 69.400002
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalPitchDegree = -60.000000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:FlightRollDegree = -2.100000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:FlightYawDegree = 69.699997
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:FlightPitchDegree = …
```
=> Allow Application Notes (XMP) in SubIFD

MetadataExtractor/Formats/Png/PngMetadataReader.cs
test if "IPTC" profile is stored as either IPTC IIM or a Photoshop IRB resource
closes #280
=> test "IPTC" profile type

MetadataExtractor/Formats/Tiff/TiffReader.cs
Port of https://github.com/drewnoakes/metadata-extractor/pull/548
Thanks to @fclof for finding this.
=> Fix reading arrays of Float64 in TIFF files

MetadataExtractor/DirectoryExtensions.cs, MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Photoshop/PhotoshopTiffHandler.cs, MetadataExtractor/Formats/QuickTime/QuickTimeTiffHandler.cs, MetadataExtractor/Formats/Tiff/DirectoryTiffHandler.cs, MetadataExtractor/Formats/Tiff/ITiffHandler.cs, MetadataExtractor/Formats/Tiff/TiffDataFormat.cs, MetadataExtractor/Formats/Tiff/TiffReader.cs, MetadataExtractor/Formats/Tiff/TiffStandard.cs, MetadataExtractor/IO/IndexedReader.cs, MetadataExtractor/PublicAPI/net35/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, MetadataExtractor/Util/FileTypeDetector.cs
Note that while BigTIFF supports files greater than 2 GiB in size, our current implementation does not due to the pervasive use of Int32 throughout the code to represent offsets into the data.
This PR involves several API changes. These are public APIs, but are unlikely to be used directly by user code.
=> Support BigTIFF encoded TIFF data

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs, MetadataExtractor/Formats/Exif/makernotes/PentaxType2MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/PentaxType2MakernoteDirectory.cs, MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
=> Basic Pentax Type 2 makernote support

azure-pipelines.yml
CI is broken, failing with messages:
```
##[error]Testhost process for source(s) 'D:\a\1\s\MetadataExtractor.Tests\bin\Release\net6.0\Microsoft.TestPlatform.CoreUtilities.dll' exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
##[error]Failed to run as a self-contained app.
##[error]  - The application was run as a self-contained app because 'D:\a\1\s\MetadataExtractor.Tests\bin\Release\net6.0\testhost.runtimeconfig.json' was not found.
##[error]  - If this should be a framework-dependent app, add the 'D:\a\1\s\MetadataExtractor.Tests\bin\Release\net6.0\testhost.runtimeconfig.json' file and specify the appropriate framework.
##[error]. Please check the diagnostic logs for more …
```
=> Fix test assembly discovery

MetadataExtractor/Formats/Png/PngMetadataReader.cs
Fixes #328
Parse the keyword and text directory using utf8 encoding if PNG Chunk Type is iTXt
=> Fixes Issue #328

Directory.Build.props
This prevents causing consumers of the MetadataExtractor package from also picking up these analyzers transitively.
=> Make analyzer private

MetadataExtractor/IO/ByteArrayReader.cs, MetadataExtractor/IO/IndexedCapturingReader.cs, MetadataExtractor/IO/IndexedReader.cs, MetadataExtractor/IO/IndexedSeekingReader.cs, MetadataExtractor/PublicAPI/net35/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Fixes #62
Adds a new abstract overload for reading a single byte. That method will not do any explicit bounds validation, so callers must do that beforehand. In cases where multiple bytes are read, the validation can be performed once per value, rather than once per byte.
=> Remove excessive bounds checking in IndexedReader

MetadataExtractor.Tests/.editorconfig, MetadataExtractor.Tests/MetadataExtractor.Tests.csproj, MetadataExtractor.Tests/StringValueTest.cs, MetadataExtractor/Formats/Avi/AviRiffHandler.cs, MetadataExtractor/Formats/Exif/Makernotes/NikonPictureControl1Directory.cs, MetadataExtractor/PublicAPI/net35/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, MetadataExtractor/StringValue.cs
Fix NikonPictureControl1Directory string reading. These fixed-width, null-terminated strings. We don't want those nulls in the string we return.
Also some minor tidying and adding a unit test.
=> Fix NikonPictureControl1Directory parsing

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
Added code to parse OM System II makernote (uses Olympus II makernote) by checking the signature in ProcessMakernote (matches andydragon/omsystem PR in metadata-extractor and andydragon/omsystem PR in metadata-extractor-images)
=> Added code to parse OM System II makernote (uses Olympus II makernote)

MetadataExtractor/Formats/Xmp/XmpReader.cs, MetadataExtractor/MetadataExtractor.csproj
Fixes #356
Software that re-writes XMP can do so without changing the size of the XMP segment. If it overwrites the data with a shorter payload, there can be junk at the end which causes the XML parsing to fail.
This change adds a scan for known end-of-message markers, to avoid this problem.
=> Work around invalid XMP XML

MetadataExtractor/Formats/Apple/BplistReader.cs, MetadataExtractor/Formats/Eps/EpsReader.cs, MetadataExtractor/Formats/Exif/ExifReader.cs, MetadataExtractor/Formats/Icc/IccReader.cs, MetadataExtractor/Formats/Iso14496/Boxes/ColorInformationBox.cs, MetadataExtractor/Formats/Jfif/JfifReader.cs, MetadataExtractor/Formats/Jfxx/JfxxReader.cs, MetadataExtractor/Formats/Jpeg/JpegSegmentWithPreambleMetadataReader.cs, MetadataExtractor/Formats/Photoshop/PhotoshopReader.cs, MetadataExtractor/Formats/Png/PngChunkReader.cs, MetadataExtractor/Formats/QuickTime/QuickTimeTypeChecker.cs, MetadataExtractor/Formats/Riff/RiffTypeChecker.cs, MetadataExtractor/Formats/Tga/TgaFooterReader.cs, MetadataExtractor/Util/ByteArrayExtensions.cs, MetadataExtractor/Util/ByteTrie.cs, MetadataExtractor/Util/FileTypeDetector.cs
Posting for early feedback. 
There is one public API change, which I'm happy to revert if we have a no-breaking changes policy.
`protected byte[] PreambleBytes` was changed to `protected ReadOnlySpan<byte> PreambleBytes`
This also prevents the mutation of the underlying data.
=> Spanify various things and use UTF-8 literals

MetadataExtractor.Tests/MetadataExtractor.Tests.csproj
I'm seeing a ~35% reduction in test time here after the update.
=> Run tests against net8.0 & update xunit

MetadataExtractor.Tests/DirectoryExtensionsTest.cs, MetadataExtractor.Tests/DirectoryTest.cs, MetadataExtractor.Tests/Formats/Adobe/AdobeJpegReaderTest.cs, MetadataExtractor.Tests/Formats/Exif/ExifReaderGremlinTest.cs, MetadataExtractor.Tests/Formats/Exif/ExifReaderTest.cs, MetadataExtractor.Tests/Formats/Exif/ExifSubIFDDescriptorTest.cs, MetadataExtractor.Tests/Formats/Icc/IccReaderTest.cs, MetadataExtractor.Tests/Formats/Jpeg/JpegSegmentReaderTest.cs, MetadataExtractor.Tests/Formats/Netpbm/NetpbmReaderTest.cs, MetadataExtractor.Tests/Formats/Png/PngDescriptorTest.cs, MetadataExtractor.Tests/IO/IndexedReaderTestBase.cs, MetadataExtractor.Tests/IO/SequentialReaderTestBase.cs, MetadataExtractor.Tests/TagDescriptorTests.cs, MetadataExtractor.Tests/Util/ByteTrieTest.cs
Uses a few modern C# features to tidy up the tests
=> Tidy up tests

MetadataExtractor.Tests/IO/SequentialReaderTestBase.cs, MetadataExtractor/IO/SequentialByteArrayReader.cs, MetadataExtractor/IO/SequentialReader.cs, MetadataExtractor/IO/SequentialStreamReader.cs, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
Read all required bytes in one go, and use `BinaryPrimitives` class for faster conversion to built-in types.
=> Spanify SequentialReader

.editorconfig
There are use cases for both. Leave it to the author rather than enforcing either way.
=> Permit var and explicit types

MetadataExtractor.PowerShell/MetadataExtractor.PowerShell.csproj, MetadataExtractor.PowerShell/ShowJpegStructure.cs, MetadataExtractor/Formats/Adobe/AdobeJpegReader.cs, MetadataExtractor/Formats/Exif/ExifReader.cs, MetadataExtractor/Formats/Icc/IccReader.cs, MetadataExtractor/Formats/Jfif/JfifReader.cs, MetadataExtractor/Formats/Jfxx/JfxxReader.cs, MetadataExtractor/Formats/Photoshop/DuckyReader.cs, MetadataExtractor/Formats/Photoshop/PhotoshopReader.cs, MetadataExtractor/Formats/QuickTime/QuickTimeTypeChecker.cs, MetadataExtractor/Formats/Xmp/XmpReader.cs, MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt, MetadataExtractor/Util/ByteTrie.cs
@drewnoakes Ready for review / feedback.
Note: The AdobeJpegReader compares the Preamble using a case-insensitive comparer in ReadJpegSegments, while it uses an ordinal comparer when reading segments. From what I can tell in the specifications, this should be exact, but I didn't want to change behavior here.
=> Update JpegSegmentPreamble to UTF-8 spans

.editorconfig, MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
It's important that public API changes are flagged during code review, and the API files really help surface such changes. This diagnostic should be marked as an error.
=> Make missing APIs an error

.editorconfig, MetadataExtractor.Tests/IO/IndexedReaderTestBase.cs, MetadataExtractor/IO/ByteArrayReader.cs, MetadataExtractor/IO/IndexedCapturingReader.cs, MetadataExtractor/IO/IndexedReader.cs, MetadataExtractor/IO/IndexedSeekingReader.cs, MetadataExtractor/IO/SequentialStreamReader.cs, MetadataExtractor/PublicAPI/net462/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
Allows avoidance of temporary byte arrays, reduces the number of virtual calls to `GetByteInternal`, and uses conversion methods optimised by the framework (e.g. `BinaryPrimitives`).
=> Spanify indexed reader classes

MetadataExtractor/IO/IndexedReader.cs, MetadataExtractor/IO/SequentialReader.cs, MetadataExtractor/MetadataExtractor.csproj, MetadataExtractor/Util/EncodingExtensions.cs
Originally proposed by @iamcarbon in https://github.com/drewnoakes/metadata-extractor-dotnet/pull/380#discussion_r1468653528
This requires allowing unsafe blocks for `net462` and `netstandard1.3`.
=> Polyfill non-allocating encoding span->string without byte[]

Directory.Build.props, LICENSE, MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs, MetadataExtractor.PowerShell/ShowJpegStructure.cs, MetadataExtractor/DirectoryExtensions.cs, MetadataExtractor/Formats/Exif/makernotes/CanonMakernoteDescriptor.cs, MetadataExtractor/Formats/Png/PngChunkType.cs, MetadataExtractor/GeoLocation.cs, MetadataExtractor/TagDescriptor.cs, MetadataExtractor/Util/ByteConvert.cs, MetadataExtractor/Util/DateUtil.cs
Since the advent of nullable reference types, these annotations aren't adding much value.
=> Remove JetBrains.Annotations

Directory.Build.props
Now that we're moving to building and pushing packages via GitHub actions, we will take the version from the release itself. This means we don't want it to be specified in the file directly.
I like this change as it means we don't have to keep the props file in sync with the current version, simplifying the release process somewhat. We only have to bump the version in the README which directs users to install the current version. That can always be done after release if missed.
=> Remove explicit Version MSBuild property

MetadataExtractor/Formats/Exif/makernotes/OlympusCameraSettingsMakernoteDescriptor.cs, MetadataExtractor/Formats/QuickTime/QuickTimeReaderExtensions.cs
Running `main` against the regression suite showed a few small regressions which are fixed here.
=> Address minor regressions

MetadataExtractor/Formats/Apple/BplistReader.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusCameraSettingsMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusMakernoteDirectory.cs, MetadataExtractor/Formats/Flir/FlirReader.cs, MetadataExtractor/Formats/Jpeg/JpegReader.cs, MetadataExtractor/Formats/Photoshop/PhotoshopReader.cs, MetadataExtractor/Formats/Png/PngChromaticities.cs, MetadataExtractor/Formats/Png/PngDescriptor.cs, MetadataExtractor/Formats/Png/PngHeader.cs, MetadataExtractor/Formats/Png/PngMetadataReader.cs, MetadataExtractor/Formats/QuickTime/QuickTimeReaderExtensions.cs, MetadataExtractor/Formats/Wav/WavFactHandler.cs, MetadataExtractor/IO/BufferReader.cs
This PR introduces a ref struct based BufferReader that can operate directly over a span -- and applies it to eliminate a bunch of random allocations. 
This same approach can also be used to optimize various Extract functions with a public API change.
=> Introduce BufferReader and eliminate a bunch of allocations

MetadataExtractor.Tools.FileProcessor/DeconstructionExtensions.cs, MetadataExtractor.Tools.FileProcessor/Program.cs, MetadataExtractor.Tools.FileProcessor/UnknownTagHandler.cs
This utility reports the most common unknown tags in a series of images. Using this we can find which common tags we do not yet understand, in order to prioritise investments in expanding support.
<details><summary>Output from metadata-extractor-images</summary>
Note that frequency depends upon the number of samples we have for the given metadata. This data is still helpful regardless.
```
Processed 1,863 files (read 430,858,216 of 3,392,364,647 bytes) with 150 exceptions and 693 file errors
PrintIM, 0x0101, 168
PrintIM, 0x0002, 167
PrintIM, 0x0003, 126
PrintIM, 0x0001, 108
PrintIM, 0x0100, 108
Canon Makernote, 0xC100, 104
Canon Makernote, 0xC400, 104
Canon Makernote, 0xC40B, 104
Canon Makernote, 0xC419, 103
PrintIM, 0x000A, 103
PrintIM, 0x000C, 103
PrintIM, 0x000D, 103
PrintIM, 0x000E, …
```
=> Port UnknownTagHandler

MetadataExtractor/Formats/Exif/makernotes/AppleMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/AppleMakernoteDirectory.cs, MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
These were some of the most common unrecognised tags in our sample data.
=> Extend Apple makernote support

MetadataExtractor/PublicAPI/net462/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt, MetadataExtractor/Tag.cs
These have been obsolete for a long time. Remove them as part of the API changes in 2.9.0.
=> Remove obsolete members on Tag class

MetadataExtractor/Formats/Tiff/TiffReader.cs
Traces gathered over the test suite show:
- ~2.7% CPU spent in `IndexedReader.GetByte(int)`
- ~0.4% CPU spent in `IndexedReader.GetSByte(int)`
Looking at the main callers shows loops in `TiffReader` that call these methods in loops. This approach accrues overhead per-byte due to bounds checking and virtual dispatch.
Instead, use the `Span<byte>` overload of `GetBytes` that performs the bounds checking once, then copies data in a single call.
It may be possible to give a similar treatment to the handling of other TIFF format codes, though they're not currently showing up on traces and would be more complex to implement due to byte-ordering issues (`byte` and `sbyte` being immune from those).
=> Reduce overhead reading byte/sbyte arrays from IndexedReader

MetadataExtractor/Formats/Png/PngMetadataReader.cs, MetadataExtractor/Formats/Tiff/TiffMetadataReader.cs, MetadataExtractor/IO/IndexedCapturingReader.cs, MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
Looking at traces over the regression suite shows ~2% CPU spent allocating chunks for the `IndexedCapturingReader`.
We can pull these buffers from the array pool, and return them when we're done. When processing multiple items, reusing these arrays will improve overall performance.
=> Pool buffers in IndexedCapturingReader

MetadataExtractor/Formats/Icc/IccDescriptor.cs
Analysing some CPU traces showed ~0.5% of sampled CPU stacks were hitting this number formatting function. The code itself looks pretty wild and I'm very happy to be removing it. Half a percent may not seem high, but this is one of the highest CPU consuming methods of the library in the trace, which is definitely not expected.
Looks like it was ported over from Java: https://github.com/drewnoakes/metadata-extractor/blob/b19ac0637ff1481bed8029130a9e8669267b4980/Source/com/drew/metadata/icc/IccDescriptor.java#L227-L246. A similar fix would be good there.
=> Remove custom number formatting in ICC

MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
Reduces allocations and CPU when deciding what decoding policy to use for makernote processing.
=> Spanify top-level parsing for makernotes

MetadataExtractor/Formats/Tiff/TiffReader.cs
Previously we would read values one-at-a-time through IFD tables of TIFF data. There's a fair amount of indirection here.
With this code, we load the entire IFD table into a span (ideally on the stack) and read through it from there. This was identified in traces as a nice perf win.
As part of this work, constants were added to indicate the sizes involved, and some variable names were made clearer.
Also, the size restriction placed on IFDs was improved, so that they aren't required to have space at the end for the optional follower IFD pointer, fixing some cases in the regression suite.
=> TIFF extraction makes fewer, larger reads

MetadataExtractor/ImageMetadataReader.cs, MetadataExtractor/PublicAPI/net462/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt, MetadataExtractor/Util/FileType.cs, MetadataExtractor/Util/FileTypeDetector.cs
Several camera raw files share the same opening bytes, and our current prefix detection cannot differentiate between then. This change allows the file path to be provided, to be used when certain byte prefixes are seen.
=> Allow filename to influence file type detection

MetadataExtractor/Formats/Apple/BplistReader.cs, MetadataExtractor/IO/BufferReader.Indexed.cs, MetadataExtractor/IO/BufferReader.Sequential.cs, MetadataExtractor/IO/IndexedReader.cs, MetadataExtractor/IO/ScopedBuffer.cs, MetadataExtractor/IO/SequentialReader.cs, MetadataExtractor/Util/DateUtil.cs
This PR extracts the ScopedBuffer work from #406
Local regression testing shows no diffs.
@drewnoakes Ready for review.
=> Introduce ScopedBuffer

MetadataExtractor/Formats/Apple/BplistReader.cs, MetadataExtractor/Formats/Exif/Makernotes/AppleRunTimeMakernoteDirectory.cs, MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
This PR spanifies a couple of methods on BplistReader. No regressions were detected in the image library.
@drewnoakes Ready for review.
=> Spanify BplistReader

MetadataExtractor/IO/SequentialStreamReader.cs
Fixes #428
Skip Method: Avoid an integer overflow bug by explicitly casting to ulong before comparing the expression.
=> SequentialStreamReader.cs: Cast numbers to ulong before bound check

MetadataExtractor/Formats/Icc/IccDescriptor.cs
Prompted by drewnoakes/metadata-extractor#687 and achieving essentially the same behaviour, though that version throws rather than returning null.
=> Fix a bounds check in ICC tag decoding

MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs, MetadataExtractor/Formats/Exif/ExifDirectoryBase.cs, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
Humidity, pressure, temperature, water depth, acceleration, camera elevation angle.
=> Support additional Exif tags

MetadataExtractor/Formats/Avi/AviRiffHandler.cs, MetadataExtractor/Formats/Bmp/BmpHeaderDescriptor.cs, MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs, MetadataExtractor/Formats/Exif/GpsDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/OlympusCameraSettingsMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/PanasonicMakernoteDescriptor.cs, MetadataExtractor/Formats/Exif/makernotes/SigmaMakernoteDescriptor.cs, MetadataExtractor/Formats/Flir/FlirCameraInfoDescriptor.cs, MetadataExtractor/Formats/Jpeg/JpegDhtReader.cs, MetadataExtractor/Formats/Tiff/TiffReader.cs, MetadataExtractor/GeoLocation.cs, MetadataExtractor/IO/SequentialStreamReader.cs, MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
- Reduce allocations in CFA pattern decoding
- Remove redundant parentheses
- Introduce `==` and `!=` operators in `GeoLocation`
- General formatting
=> Performance and code style
