drewnoakes/metadata-extractor-dotnet

- MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs
- MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDescriptor.cs
- MetadataExtractor/TagDescriptor.cs
Completes to-do in commit ea3d8dc 
Tested against images database and couldn't find any differences. You should verify.
> Describe ExifDescriptorBase.TagLensSpecification to match Java

- MetadataExtractor.Tests/MetadataExtractor.Portable.Tests.csproj
- MetadataExtractor.Tests/MetadataExtractor.Tests.csproj
- MetadataExtractor/DirectoryExtensions.cs
- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxMakernoteDirectory.cs
- MetadataExtractor/MetadataExtractor.Portable.csproj
- MetadataExtractor/MetadataExtractor.net35.csproj
- MetadataExtractor/MetadataExtractor.net45.csproj
Moving ahead with a pull request for lack of response on metadata-extractor-dev.  Changes here should be OK on the basics but some style adjustment and trimming the .jpg into a binary fragment may be desirable.  Please advise.  I looked round a bit for guidance on the trimming process and how to get the right part of the file but didn't spot any.
> support Reconyx makernote

- MetadataExtractor/DirectoryExtensions.cs
- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxMakernoteDirectory.cs
Minor adjustment to present two of the directory tags more helpfully.
> Reconyx makernote improvements

- MetadataExtractor/Formats/Jpeg/JpegCommentDirectory.cs
- MetadataExtractor/Formats/Jpeg/JpegCommentReader.cs
> JpegCommentDirectory stores StringValue

- MetadataExtractor/Formats/Exif/ExifReader.cs
- MetadataExtractor/Formats/Exif/makernotes/OlympusMakernoteDirectory.cs
- MetadataExtractor/Formats/Png/PngColorType.cs
- MetadataExtractor/Formats/Png/PngHeader.cs
- MetadataExtractor/Formats/Png/PngMetadataReader.cs
- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
- MetadataExtractor/Formats/WebP/WebpRiffHandler.cs
> Remove calls to Debug.WriteLine #61

- MetadataExtractor.Tests/Formats/Exif/NikonType2MakernoteTest.cs
- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Exif/makernotes/NikonType2MakernoteDirectory.cs
- MetadataExtractor/Formats/Exif/makernotes/SanyoMakernoteDirectory.cs
Handles 0x0E00 tags as PrintIM and updates the PrintIM unit test
> Finish off PrintIM support in current directories

- MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs
- MetadataExtractor/Formats/Exif/ExifDirectoryBase.cs
- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Exif/makernotes/OlympusEquipmentMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/OlympusFocusInfoMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/PanasonicMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/RicohMakernoteDescriptor.cs
- MetadataExtractor/Formats/Iptc/IptcReader.cs
- MetadataExtractor/TagDescriptor.cs
... in conjunction with Java version to make images output closer.
> Various formatting fixes and cleanup

- MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs
#81 
Formats CFAPattern2 (0x828E) the same as CFAPattern (0xA302). Requires RepeatPatternDim (0x828D) to exist and have a validated byte array. The final format is created with FormatCFAPattern for both CFA pattern tags, which is a port from Exiftool. You're free to change the final output in that function if you want something different, although the bracket format isn't bad for the data.
> Apply color lookup format to CFAPattern2

- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
This addresses #102 
It seems like HasFollowerIfd was over-thinking what to do, at least for JPEG and some TIFF formats. The spec indicates 'nextIfdOffset' from TiffReader.cs should point at some kind of image (it's the next 'Image file directory' after all).
This isn't exhaustive, but for now if the current Ifd is IFD0, the next Ifd (IFD1) is a thumbnail. Otherwise, it's treated as another image such as in a multi-page TIFF case. Please give it some thought and let me know.
(I don't think the CanonMakernote comment is valid anymore with all the change to Canon makernote parsing. I could be wrong though)
> Always assume follower ifd's point to a thumb or image

- MetadataExtractor/Formats/Exif/makernotes/DJIMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/DJIMakernoteDirectory.cs
- MetadataExtractor/MetadataExtractor.csproj
Now supports the EXIF information placed by DJI aircraft (Aircraft Pitch/Roll/Yaw, Camera Pitch/Roll/Yaw, and GPS Lat/Lon/Elevation).
> Added DJI EXIF read capability

- MetadataExtractor/Formats/Exif/ExifDescriptorBase.cs
> implement #141

- MetadataExtractor/Formats/Gif/GifReader.cs
port drewnoakes/metadata-extractor#367 from Java
Note that .NET uses the 'yield return' logic. This needed a null check to make sure it doesn't return null directories. Not an issue in Java because the 'metadata' object is passed around and would never set the directory in this case.
> port #367 from Java

- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
- MetadataExtractor/Formats/QuickTime/QuickTimeTrackHeaderDirectory.cs
- MetadataExtractor/IO/SequentialReader.cs
I've added parsing for track rotation for quick time meta data. 
Fixes #149
> Added support for rotation of QuickTime meta data.

- MetadataExtractor/Formats/Jpeg/JpegComponent.cs
- MetadataExtractor/Formats/Jpeg/JpegDescriptor.cs
This ports https://github.com/drewnoakes/metadata-extractor/pull/235 to .NET
Closes #88
> Perform formatting of JpegComponent in ToString()

- MetadataExtractor/DirectoryExtensions.cs
> Fix range bug in DirectoryExtensions.GetInt64

- MetadataExtractor/Formats/Png/PngMetadataReader.cs
Todo on Java - investigate whether this line is redundant:
https://github.com/drewnoakes/metadata-extractor/blob/81143f746e6774eb7625e374b3f6e56396288d1a/Source/com/drew/imaging/png/PngMetadataReader.java#L180
> catch PngMetadataReader iCCP decompression errors to match Java output

- MetadataExtractor.Tools.FileProcessor/FileHandlerBase.cs
- MetadataExtractor.Tools.FileProcessor/TextFileOutputHandler.cs
Part of https://github.com/drewnoakes/metadata-extractor-images/issues/20
> Generate metadata files under a 'dotnet' folder

- MetadataExtractor/Formats/Gif/GifReader.cs
Port of drewnoakes/metadata-extractor#254
> port of Java #254

- MetadataExtractor/Formats/Xmp/XmpReader.cs
> Port of Java issue #394

- Directory.Build.props
> Fix package license

- .editorconfig
- MetadataExtractor.sln
> Add .editorconfig for style consistency.

- MetadataExtractor/Formats/Exif/makernotes/OlympusRawDevelopment2MakernoteDescriptor.cs
port of Java drewnoakes/metadata-extractor#339
> port of Java issue #339

- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxHyperFire2MakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/ReconyxHyperFire2MakernoteDirectory.cs
> Add support for Reconyx type 3 tags

- MetadataExtractor.sln.DotSettings
- MetadataExtractor/Formats/Mpeg/Mp3Descriptor.cs
- MetadataExtractor/Formats/Mpeg/Mp3Directory.cs
- MetadataExtractor/Formats/Mpeg/Mp3MetadataReader.cs
- MetadataExtractor/Formats/Mpeg/Mp3Reader.cs
- MetadataExtractor/Formats/Mpeg/MpegAudioTypeChecker.cs
- MetadataExtractor/Formats/Photoshop/PsdReader.cs
- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
- MetadataExtractor/ImageMetadataReader.cs
- MetadataExtractor/Util/FileType.cs
- MetadataExtractor/Util/FileTypeDetector.cs
This port's @payton's excellent contribution to the Java library to the .NET one.
> Port MP3 support from Java

- MetadataExtractor.Tests/DirectoryTest.cs
- MetadataExtractor/DirectoryExtensions.cs
PR for issue https://github.com/drewnoakes/metadata-extractor-dotnet/issues/257
> Support for ISO8601 format in directory GetDateTime

- MetadataExtractor.PowerShell/ShowJpegStructure.cs
- MetadataExtractor.Tests/Util/ByteTrieTest.cs
- MetadataExtractor/Formats/QuickTime/QuickTimeTypeChecker.cs
- MetadataExtractor/PublicAPI/net35/PublicAPI.Shipped.txt
- MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt
- MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
- MetadataExtractor/Util/ByteTrie.cs
Relates to drewnoakes/metadata-extractor#490.
> Support Nokia 6.1 MP4 file type

- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
> Prevent divide by zero

- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
Addresses the .NET side of https://github.com/drewnoakes/metadata-extractor/issues/505.
> Fix Samsung makernote detection

- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/Photoshop/PhotoshopTiffHandler.cs
- MetadataExtractor/Formats/Tiff/DirectoryTiffHandler.cs
- MetadataExtractor/Formats/Tiff/ITiffHandler.cs
- MetadataExtractor/Formats/Tiff/IfdIdentity.cs
- MetadataExtractor/Formats/Tiff/TiffReader.cs
- MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Fixes https://github.com/drewnoakes/metadata-extractor-dotnet/issues/304
> Improve cycle detection within TIFF data

- MetadataExtractor.Samples/GeoTiffSamples.cs
- MetadataExtractor.Samples/MetadataExtractor.Samples.csproj
- MetadataExtractor/Formats/Exif/ExifDirectoryBase.cs
This sample code determines the corner positions of a GeoTIFF image in latitude/longitude.
> Add GeoTIFF sample

- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataHeaderDirectory.cs
- MetadataExtractor/PublicAPI/net35/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/net45/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
> Add QuickTime android value tags

- MetadataExtractor/Formats/Exif/GpsDescriptor.cs
> Fix bug in GpsDescriptor.GetGpsDestLongitudeDescription

- MetadataExtractor/Formats/Png/PngMetadataReader.cs
> Check for exif preamble

- MetadataExtractor.Tests/Formats/Iptc/Iso2022ConverterTest.cs
- MetadataExtractor/Formats/Iptc/Iso2022Converter.cs
Ports drewnoakes/metadata-extractor#615
> Port IPTC encoding fix from Java library

- MetadataExtractor/Formats/Exif/makernotes/FujifilmMakernoteDescriptor.cs
- MetadataExtractor/Formats/Exif/makernotes/FujifilmMakernoteDirectory.cs
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt
This ports over the improvements made by @danielsz in https://github.com/drewnoakes/metadata-extractor/pull/619
> Port Fujifilm makernote improvements

- MetadataExtractor/Formats/Exif/makernotes/SonyType1MakernoteDescriptor.cs
Ports https://github.com/drewnoakes/metadata-extractor/pull/641
> Fix incorrect descriptor in Sony Type1 makernote

- MetadataExtractor/Formats/Exif/ExifTiffHandler.cs
- MetadataExtractor/Formats/GeoTiff/GeoTiffDescriptor.cs
- MetadataExtractor/Formats/GeoTiff/GeoTiffDirectory.cs
Port functional changes from #324, minus test data.
> Extend GeoTIFF support

- MetadataExtractor/Formats/QuickTime/QuickTimeTypeChecker.cs
- MetadataExtractor/PublicAPI/net45/PublicAPI.Shipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Shipped.txt
- MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
- MetadataExtractor/Util/ByteTrie.cs
> Spanify ByteTrie.Find

- MetadataExtractor/Formats/QuickTime/QuickTimeTypeChecker.cs
- MetadataExtractor/ImageMetadataReader.cs
- MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
- MetadataExtractor/Util/FileType.cs
Ported from https://github.com/drewnoakes/metadata-extractor/pull/649
> Add AVIF support

- MetadataExtractor/IO/IndexedSeekingReader.cs
- MetadataExtractor/IO/SequentialStreamReader.cs
Update the conditional symbols.
> Use spans in readers in .NET 8

- MetadataExtractor/PublicAPI/net462/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard1.3/PublicAPI.Unshipped.txt
- MetadataExtractor/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
- MetadataExtractor/Util/FileType.cs
- MetadataExtractor/Util/FileTypeDetector.cs
Prompted by drewnoakes/metadata-extractor#665
> Add file type detection for PDF

- MetadataExtractor/TagDescriptor.cs
> Fix shutter speed description calculation

- MetadataExtractor/Formats/QuickTime/QuickTimeMetadataReader.cs
…software.
"XMP_" atom within a "udta" atom, within a top level "moov" atom.
> Added support for xmp in quicktime files as written by latest Adobe software

- MetadataExtractor/Formats/Png/PngMetadataReader.cs
> Fixed PNG compressed iTXt chunk

- README.md
> Add CR3 as a supported file type to the README
